# Prettier configuration
overrides:
  - files:
      - "*.java"
    options:
      tabWidth: 4
      useTabs: false
      printWidth: 80
  - files:
      - "*.xml"
    options:
      xmlWhitespaceSensitivity: ignore
